Setup AMBuild 2.2 + Github Action + Removed threaded nav
TF2-DMB/CBaseNPC pull request #11
Opened 2021-11-13 01:44 UTC by Kenzzer

We're moving to AMBuild 2.2 so MSCV is properly detected in github actions environment. As well as getting the field ready for CSGO & multi platform support.

`master` branch is now fully protected, every pull requests must be squashed and merged and have at least one review. Finally the action from this commit will be required to succeed in order to allow merging of any PRs.

Finally, the threaded nav code has been fully removed, as it prevents compilation of the ext against sm 1.10 and isn't thread safe anyways. It may eventually be revisited in the future.

2021-11-13 02:12 UTC, KitRifty requested changes
Mostly everything looks in order to me. The only major thing I can point out is the removal of the the `CNavMesh::AddNavArea()` detour.

Also in addition to the automatic builder, are there plans to implement an automatic release action as well? It would be convenient to have a system in place that would zip up the build artifacts and game data all in one package allowing for easy installation.

2021-11-13 02:16 UTC, Kenzzer commented on extension/extension.cpp
> -DETOUR_DECL_MEMBER1(CNavMesh_AddNavArea, void, CNavArea*, area)
Wouldn't it make more sense to re-introduce the detour within navmesh.cpp ?

2021-11-13 02:17 UTC, KitRifty commented on extension/extension.cpp
> -DETOUR_DECL_MEMBER1(CNavMesh_AddNavArea, void, CNavArea*, area)
Actually yes, it'll help with organization for sure.

2021-11-13 02:18 UTC, Kenzzer commented
I'm unfamiliar with release action but yes, this would be very much needed on this repo.

2021-11-13 23:51 UTC, Kenzzer commented
Any commit on master will now create a CBaseNPC release. After this lands, it will be very important we update `product.version` file when fixing/adding in new features.

2021-11-14 00:07 UTC, KitRifty approved these changes
Everything in the workflow file looks to be in order, so I'm trusting that you've done some testing with this beforehand. I would like some sort of automation with the versioning so we wouldn't need to edit `product.file` every time, but this can be done in the future in another PR.

Overall, very nice work!

2021-11-14 00:10 UTC, merged