Revise natives code
TF2-DMB/CBaseNPC pull request #40
Opened 2023-07-22 18:25 UTC by Kenzzer

# What's changed ?

Instead of all the natives being inside various include files, and then all included by `natives.h` we instead divide those natives into multiple `.hpp` and `.cpp` files, available in the `natives` directory. Very much mirroring the setup of our .inc files.

# New way to register natives

No more global array, instead an std::vector is passed around by reference. The natives are then added to it by each `.cpp` module. Furthermore, macros to define native functions have been eliminated. Everything are now locally defined functions, only available in their respective `.cpp` file.

Example :
```cpp
void setup(std::vector<sp_nativeinfo_t>& natives) {
	area::setup(natives);
	surroundingareas::setup(natives);
	
	tf::nav::setup(natives);

	sp_nativeinfo_t list[] = {
		{"CNavMesh.Address.get", GetAddress},
		{"CNavMesh.IsLoaded", IsLoaded},
		{"CNavMesh.IsAnalyzed", IsAnalyzed},
		{"CNavMesh.IsOutOfDate", IsOutOfDate},
		{"CNavMesh.GetNavAreaCount", GetNavAreaCount},
		{"CNavMesh.CollectSurroundingAreas", CollectSurroundingAreas},
		{"CNavMesh.GetNavAreaByID", GetNavAreaByID},
		{"CNavMesh.GetNearestNavArea", GetNearestNavArea},
		{"CNavMesh.BuildPath", BuildPath},
		{"CNavMesh.GetNavArea", GetNavArea},
		{"CNavMesh.GetNavAreaEntity", GetNavAreaEntity},
	};

	natives.insert(natives.end(), std::begin(list), std::end(list));
}
```

# New coding style for `{}`

As of this PR, I wish that we adopt Rust's styling for `.cpp` and `.hpp` files. The extension never had a coding style to begin with, so I believe this is a good point to start introducing some.

# New/updated natives

- Added the following natives to the extension. The usefulness and 0 gamedata cost more than enough warrants the addition of such a useful methodmap to the extension.
```
CTakeDamageInfo.CTakeDamageInfo
GetInflictor
SetInflictor
GetWeapon
SetWeapon
GetAttacker
SetAttacker
GetDamage
SetDamage
GetMaxDamage
SetMaxDamage
ScaleDamage
AddDamage
SubtractDamage
GetDamageBonus
SetDamageBonus
GetDamageBonusProvider
GetBaseDamage
BaseDamageIsValid
GetDamageForce
SetDamageForce
ScaleDamageForce
GetDamageForForceCalc
SetDamageForForceCalc
GetDamagePosition
SetDamagePosition
GetReportedPosition
SetReportedPosition
GetDamageType
SetDamageType
AddDamageType
GetDamageCustom
SetDamageCustom
GetDamageStats
SetDamageStats
SetForceFriendlyFire
IsForceFriendlyFire
GetAmmoType
SetAmmoType
GetAmmoName
GetPlayerPenetrationCount
SetPlayerPenetrationCount
GetDamagedOtherPlayers
SetDamagedOtherPlayers
SetCritType
GetCritType
```

- Fixed `CBaseNPC` and `CExtNPC` natives not verifying invalid npc index. Leading to spectacular nullpointer crashes.

2023-07-22 21:51 UTC, KitRifty requested changes
Very nice work refactoring the natives code. This is much preferred over having that huge list in the main natives file. However there are a couple of types and a handful of instances where pawn addresses aren't being converted to pointers, and vice versa.

2023-07-22 21:51 UTC, KitRifty commented on extension/natives/nextbot/component.cpp
> +	INextBotComponent* component = (INextBotComponent*)param;
```suggestion
	INextBotComponent* component = (INextBotComponent*)PawnAddressToPtr(param);
```

2023-07-22 21:51 UTC, KitRifty commented on extension/natives/nextbot/component.cpp
> +	return (cell_t)(component->GetBot());
```suggestion
	return PtrToPawnAddress(component->GetBot());
```

2023-07-22 21:51 UTC, KitRifty commented on extension/natives/nextbot/eventresponder.cpp
> +	if (!weapon && params[2] != -1) {
```suggestion
	if (!weapon && params[3] != -1) {
```

2023-07-22 21:51 UTC, KitRifty commented on extension/natives/nextbot/eventresponder.cpp
> +	{
```suggestion
	if (!entity && params[2] != -1) {
```

2023-07-22 21:51 UTC, KitRifty commented on extension/natives/nextbot/intention.cpp
> +	buffer[2] = sp_ftoc( targetPoint[2] );
```suggestion
	VectorToPawnVector( buffer, targetPoint );
```

2023-07-22 21:51 UTC, KitRifty commented on extension/natives/nextbot/intention.cpp
> +	Vector vecPos(sp_ctof(pos[0]), sp_ctof(pos[1]), sp_ctof(pos[2]));
```suggestion
	Vector vecPos;
	PawnVectorToVector( pos, vecPos );
```

2023-07-22 21:51 UTC, KitRifty commented on extension/natives/nextbot/locomotion.cpp
> +	mover->ClimbLadder((CNavLadder *)(params[2]), (CNavArea *)(params[3]));
```suggestion
	mover->ClimbLadder((CNavLadder *)PawnAddressToPtr(params[2]), (CNavArea *)PawnAddressToPtr(params[3]));
```

2023-07-22 21:51 UTC, KitRifty commented on extension/natives/nextbot/locomotion.cpp
> +	mover->DescendLadder((CNavLadder *)(params[2]), (CNavArea *)(params[3]));
```suggestion
	mover->DescendLadder((CNavLadder *)PawnAddressToPtr(params[2]), (CNavArea *)PawnAddressToPtr(params[3]));
```

2023-07-22 21:51 UTC, KitRifty commented on extension/natives/nextbot/path.cpp
> +	Path::Segment* segment = (Path::Segment*)(params[4]);
```suggestion
	Path::Segment* segment = (Path::Segment*)PawnAddressToPtr(params[4]);
```

2023-07-22 21:51 UTC, KitRifty commented on extension/natives/nextbot/path.cpp
> +	INextBot* bot = (INextBot*)(params[2]);
```suggestion
	INextBot* bot = (INextBot*)PawnAddressToPtr(params[2]);
```

2023-07-22 21:51 UTC, KitRifty commented on extension/natives/nextbot/path.cpp
> +	Path* path2 = (Path*)(params[3]);
```suggestion
	Path* path2 = (Path*)PawnAddressToPtr(params[3]);
```

2023-07-22 21:51 UTC, KitRifty commented on extension/natives/nextbot/path.cpp
> +	Path::Segment* segment = (Path::Segment*)(params[4]);
```suggestion
	Path::Segment* segment = (Path::Segment*)PawnAddressToPtr(params[4]);
```

2023-07-22 21:51 UTC, KitRifty commented on extension/natives/nextbot/path.cpp
> +	Path::Segment* segment = (Path::Segment*)(params[2]);
```suggestion
	Path::Segment* segment = (Path::Segment*)PawnAddressToPtr(params[2]);
```

2023-07-23 09:07 UTC, Kenzzer commented on extension/natives/takedamageinfo.cpp
> +		{"CTakeDamageInfo.GetCritType", GetCritType},
The natives still need to be registered otherwise plugins will fail to load.

2023-07-23 14:26 UTC, KitRifty approved these changes

2023-07-23 16:00 UTC, merged